name: skhep-tutorial
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas
  - uproot
  - awkward
  - awkward-pandas
  - scikit-hep-testdata
  - vector
  - xrootd
  - fsspec-xrootd
  - matplotlib
  - particle
  - hepunits
  - requests
  - aiohttp
  - boost-histogram
  - hist
  - iminuit
  - zfit>=0.27.0
  - fastjet
  - jupyterlab-myst
